### ISSUE TITLE
PersistentContainer findBundle Returning Incorrect Bundle

### ISSUE THREAD

**Issue by fishcharlie** [RichardBlanch/Einstein#1]
In the PersistentContainer init method there are the following two lines:

https://github.com/RichardBlanch/Einstein/blob/5a304fd7fa6b9d5de22c638d7572e2f790727c01/Sources/Einstein/Shared/Core%20Data/PersistentContainer.swift#L35-L36

The static `findBundle` method refers to this method:

https://github.com/RichardBlanch/Einstein/blob/5a304fd7fa6b9d5de22c638d7572e2f790727c01/Sources/Einstein/Shared/Core%20Data/PersistentContainer.swift#L161-L165

When printing all bundles `po Bundle.allBundles` I get the following results (`MyApp` changed from something else since this is a public form):

```
▿ 3 elements
  - 0 : NSBundle </Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/CoreServices/CoreGlyphs.bundle> (not yet loaded)
  - 1 : NSBundle </Users/charliefish/Library/Developer/CoreSimulator/Devices/15038C5F-BCEB-41DE-B05E-01DD23427E94/data/Containers/Bundle/Application/DF1D9447-D513-4FE5-AF79-D42DC1C5C99C/MyApp.app> (loaded)
  - 2 : NSBundle </Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/Artwork.bundle> (not yet loaded)
```

When trying to print which bundle it will return, I get the following result:

```
(lldb) po Bundle.allBundles.first(where: { $0.urls(forResourcesWithExtension: "momd", subdirectory: nil) != nil })
▿ Optional<NSBundle>
  - some : NSBundle </Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/CoreServices/CoreGlyphs.bundle> (not yet loaded)
```

---

Which is not correct. Therefor `PersistentContainer.findModelName(in: bundle)` is failing, so the application is reverting to the `GrioExample` model name. Which causes an application crash.

---

I have a few ideas about possible solutions to fix this, but I don't know the use case for all of this code, so it's hard to determine the best solution here.

**Comment by fishcharlie** [comment]
@RichardBlanch This can be closed, right?

**Comment by RichardBlanch** [comment]
@fishcharlie No, it's still borked. :(
